# this playbook provisions certificates signed by existing authorities
# tasks are grouped by certificate authorities and tagged for ease of use

- hosts: corebernetes
  gather_facts: false
  vars:
    local_certificate_directory: "{{ hostvars['localhost']['certificate_directory'] }}"
    local_private_key_directory: "{{ hostvars['localhost']['private_key_directory'] }}"
  tasks:
  - name: provision http certificates
    tags: ["http", "https"]
    block:
    - set_fact:
        authority_cert: "{{ local_certificate_directory }}/http.crt"
        authority_key:  "{{ local_private_key_directory }}/http.key"

    - include: tasks/x509/certificate.yaml
      vars:
        name: etcd-https
        server: true

  - name: provision etcd certificates
    tags: ["etcd"]
    block:
    - set_fact:
        authority_cert: "{{ local_certificate_directory }}/etcd.crt"
        authority_key:  "{{ local_private_key_directory }}/etcd.key"

    - include: tasks/x509/certificate.yaml
      vars:
        name: etcd-peer
        client: true
        server: true
