# target version of the container linux config transpiler to install
# https://github.com/coreos/container-linux-config-transpiler/releases
ct_version: 0.9.0 # no leading "v"

# target version of yq utility to use to combine container linux fragments
# https://github.com/mikefarah/yq/releases
yq_version: 2.3.0

coreos_config_file: "{{ global_corebernetes_directory }}/containerlinux.yaml"

coreos_fragments_directory: "{{ global_corebernetes_directory }}/fragments"

coreos_fragments_from: []

# coreos release group to install from, choose from: [stable, beta, alpha]
# https://coreos.com/releases/
coreos_release_channel: stable

# device (not partition) to install coreos to
# coreos_target_device: /dev/sdX
